import { EGameType, EGameState, ECommonUI, ELevelType } from "../common/base/UAllenum";

export class gameHelpType {
    rule_intro: string;
    paixing_info: string;
    paixing_size: string;
    rule_multiple: string;
    settlement: string;
    Compensation: string;
};

export var cfg_game_help: { [key: number]: gameHelpType } = {
    [EGameType.QZNN]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.BJ]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "",
        settlement: "",
        Compensation: "",
    },
    [EGameType.BREBG]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "",
        settlement: "",
        Compensation: "",
    },
    [EGameType.BRHH]: {
        rule_intro: "",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.BRJH]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.QZLH]: {
        rule_intro: "rule_intro",
        paixing_info: "",
        paixing_size: "",
        rule_multiple: "",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.BRNN]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.BJL]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.KPQZJH]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "",
        Compensation: "",
    },
    [EGameType.KPQZNN]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.QZJH]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "",
        Compensation: "",
    },
    [EGameType.QZNN]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.SG]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.TBJH]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "",
        Compensation: "",
    },
    [EGameType.TBNN]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.XPJH]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "",
        Compensation: "",
    },
    [EGameType.XPQZNN]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.XPQZNN]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "rule_multiple",
        settlement: "",
        Compensation: "",
    },
    [EGameType.BCBM]: {
        rule_intro: "rule_intro",
        paixing_info: "",
        paixing_size: "",
        rule_multiple: "rule_multiple",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.ZJH]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.DDZ]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "",
        rule_multiple: "",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.PDK]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "",
        rule_multiple: "",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.SSS]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "",
        settlement: "settlement",
        Compensation: "",
    },
    [EGameType.SH]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "",
        settlement: "",
        Compensation: "",
    },
    [EGameType.DZPK]: {
        rule_intro: "rule_intro",
        paixing_info: "paixing_info",
        paixing_size: "paixing_size",
        rule_multiple: "",
        settlement: "",
        Compensation: "",
    },
}